---
bibliography: ../Data/references.bib
output:
  bookdown::markdown_document2:
    base_format: "officedown::rdocx_document"
    number_sections: no
    tables:
      style: Table
      layout: autofit
      width: 1.0
      caption:
        style: Table Caption
        pre: 'Table '
        sep: ': '
      conditional:
        first_row: true
        first_column: false
        last_row: false
        last_column: false
        no_hband: false
        no_vband: true
    pandoc_args: 
      - "--metadata-file=../Header/header_common.yaml"
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
      - '--lua-filter=../Filters/pagebreaks.lua'
  bookdown::word_document2:
    tables:
      style: Table
      layout: autofit
      width: 1.0
      caption:
        style: Table Caption
        pre: 'Table '
        sep: ': '
      conditional:
        first_row: true
        first_column: false
        last_row: false
        last_column: false
        no_hband: false
        no_vband: true
    pandoc_args: 
      - "--metadata-file=../Header/header_common.yaml"
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
      - '--lua-filter=../Filters/pagebreaks.lua'
  officedown::rdocx_document:
    base_format: "bookdown::word_document2"
    number_sections: no
    tables:
      style: Table
      layout: autofit
      width: 1.0
      caption:
        style: Table Caption
        pre: 'Table '
        sep: ': '
      conditional:
        first_row: true
        first_column: false
        last_row: false
        last_column: false
        no_hband: false
        no_vband: true
    pandoc_args: 
      - "--metadata-file=../Header/header_common.yaml"
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
      - '--lua-filter=../Filters/pagebreaks.lua'
params:
  figures_in_body_lgl: !r F
  results_ls: NULL
  output_type_1L_chr: Word
  tables_in_body_lgl: !r F
abstract: "`r paste0(stringr::str_replace_all(stringr::str_replace_all(stringr::str_replace_all(stringr::str_replace_all(readLines('../Header/abstract.txt'),'\\\\\\\\textbf',''),'\\{','**'),'\\}','**'),'\\\\\\\\newline','\\\\n'),collapse=' ')`"
graphics: yes
csl: plos.csl
---

```{r echo = F}
library(officedown)
```
```{r child="../Child_RMDs/All_Content.Rmd", echo=FALSE}
```
